spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root

logging:
  level:
    org.example.mapper: debug

mybatis-plus:
  mapper-locations: classpath:org/example/mapper/xml/*.xml
  #mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: org.example.entity
  configuration:
    map-underscore-to-camel-case: true